# Check that there is correct Markdown in all files
name: Check Markdown

on:
  push:

jobs:
  check_markdown:

    runs-on: ubuntu-latest
    #env:
    #  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - uses: actions/checkout@v4

      - uses: articulate/actions-markdownlint@v1
      #  with:
      #    config: .markdownlint.jsonc
      #    ignore: .markdownlintignore
