on:
  push:

jobs:
  run_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python --version
      - run: python hello.py
      - uses: astral-sh/ruff-action@v3


